title: My awesome title
author: Lauti
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I wrote an awesome description for my new site here. I can edit this
  line in _config.yml. It will appear in my document head meta (for
  Google search results) and in my feed.xml site description.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
